name: Scrape and Notify

on:
  # Jalankan otomatis setiap 12 jam
  schedule:
    - cron: "0 */12 * * *"
  # Bisa dijalankan manual lewat GitHub UI
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the scraper and filter
      run: |
        python scripts/run_all.py
