name: Scrape LKPP Data

on:
  workflow_dispatch:     # Bisa dijalankan manual dari GitHub UI
  schedule:              # Jadwal otomatis setiap 12 jam
    - cron: '0 */12 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Jalankan scraping & filter
      run: python Notif_Paket_Baru/scripts/run_all.py

    - name: Commit perubahan data_master.csv
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add Notif_Paket_Baru/data/data_master.csv
        git commit -m 'Update data_master.csv [skip ci]' || echo "Tidak ada perubahan"
        git push
