name: Scrape LKPP Data

on:
  schedule:
    - cron: '0 2 * * *'     # 10:00 WITA
    - cron: '30 8 * * *'    # 16:30 WITA
  workflow_dispatch:        # Manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Jalankan scraping & filter
        run: python Notif_Paket_Baru/scripts/run_all.py

      - name: Commit hasil scraping
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Notif_Paket_Baru/data/data_master.csv Notif_Paket_Baru/data/hasil_scrap.csv
          git commit -m "Update data $(date +'%Y-%m-%d %H:%M:%S')" || echo "Tidak ada perubahan"
          git push
